version: '2'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - .:/usr/src/app
    depends_on:
     - redis
     - db
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: mongo
    ports:
      - "27017:27017"
